name: Docker Image CI

on:
  push:
    branches: [ "master" ] ## No branch called main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy Compose File via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_URL }}      
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/home/ubuntu/"     

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_URL }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/
          ls -la docker-compose.yml
          
          sudo docker-compose pull
          sudo docker-compose up -d --remove-orphans
          sudo docker image prune -f
          echo "Deployment Done Successfully!"
